version: '2.1'

services:
  localstack:
    container_name: "springboot-localstack"
    image: localstack/localstack
    ports:
      - "4567-4599:4567-4599"
      - "7979:8080"
    environment:
      - SERVICES=sqs,dynamodb # add other services
  dynamodb-admin:
    depends_on:
      - localstack
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4569